### ISSUE TITLE
ethminer always says there is a problem connecting

### ISSUE THREAD

**Issue by jeffdoubleyou** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#10]
Hello,

Thanks for putting this up.

I have everything installed and seems to be working but, I can't get my miner to mine anything.

There is 2 way communication between my miner and the pool and I don't see any problems but it just sits at:

JSON-RPC problem. Probably couldn't connect. Retrying in 1... 

The stats show my miner but says it doesn't have a submit hash rate method.

I'm not really sure what I'm missing or what information I can provide to you for troubleshooting, but is there anything missing in the posted code or anything?

**Comment by karek314** [comment]
Hello, You can just ignore issue with hash rate submitting.It appears something did changed in geth rpc api. Please review go-ethereum rpc api documentation and make sure that pool responds correctly to the miner after submitting hashrate.
