### ISSUE TITLE
Just a couple of questions. 

### ISSUE THREAD

**Issue by onecloudmanagement** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#14]
Hi, Thanks for posting. I am used to the NOMP Pool software, giving this one a shot. I have a few questions.

On the GETH install there are a few ways to install. is it fair to say that it is running fine if I am getting the....` I0601 18:51:11.358920 core/blockchain.go:964] imported 2048 block(s) (0 queued 0 ignored) including 2877 txs in 7.348788699s. #253404 [15e57963 / cb35ecc1]` .....messages????

On you instructions you have the requirements, done
Then the database setup in Linux and starting the pool, but there is no instructions on Installing the pool. Should I just clone the repository? 

What is the COINBASE_ADDRESS in the pool Start command?

Thanks for your patience.

**Comment by karek314** [comment]
Hi.
COINBASE_ADDRESS is your ethereum address. According to pasted log from geth - it's running fine but it's syncing. In order to start pool you need only to follow instructions and clone this repository.

**Comment by onecloudmanagement** [comment]
Thanks! That was fast.

Sent by Mobile Device
