### ISSUE TITLE
index.php not loading.

### ISSUE THREAD

**Issue by onecloudmanagement** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#15]
Hi, I an not able to load the page, I know that the directory is working since I added a php info test page and it works. I ran all the loads here with no errors.

screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8983 --rpc --unlock COINBASE_ADDRESS
screen -dmS process_work php /var/www4/block_processing/process_work/index.php
screen -dmS block_processing php /var/www4/block_processing/index.php
screen -dmS update_calculator php /var/www4/block_processing/update_calculator/index.php
screen -dmS stats php /var/www4/block_processing/stats/index.php

but are getting this error here:
root#####:~/Pool# curl http://127.0.0.1:9846/check/
curl: (7) Failed to connect to 127.0.0.1 port 9846: Connection refused

I am running on Azure, and the port is open.

Is PHP 7 good?
on the config file...  'bdd' => 'database name goes here'?

**Comment by karek314** [comment]
Are you sure that you configured nginx server block for **mainpage** directory ? Why 9846?

**Comment by onecloudmanagement** [comment]
I am using Apache. and it is configured correctly for main-page. I added the php test file there and tested it successfully. 

9846 was in your test tile. I thought it was configured as that. Where for I check this configuration?

**Comment by onecloudmanagement** [comment]
Maybe this can help see my issue...

```
root@ETHER:~/Pool/mainpage# sudo php index.php
PHP Warning:  include(/var/www4/BigInteger.php): failed to open stream: No such file or directory in /root/Pool/mainpage/index.php on line 3
PHP Warning:  include(): Failed opening '/var/www4/BigInteger.php' for inclusion (include_path='.:/usr/share/php') in /root/Pool/mainpage/index.php on line 3
PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /root/Pool/mainpage/index.php:17
Stack trace:
#0 {main}
  thrown in /root/Pool/mainpage/index.php on line 17

```

**Comment by karek314** [comment]
If your pool is not placed in **/var/www4/** then you need to correct path of **BigInteger.php** in each file.

**Comment by onecloudmanagement** [comment]
Thanks!

**Comment by onecloudmanagement** [comment]
one more Question :) (for now)

On this line screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8983 --rpc --unlock XXXXXXXXXX

Can I use any wallet address or it has to be the one I got o server install?
