### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by lukapusic** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#16]
There is a SQL injection vulnerability in the "bn" parameter.

https://ethereumpool.co/rounds/?bn=VULNERABLE
https://eth.pp.ua/rounds/?bn=VULNERABLE

**Comment by karek314** [comment]
This is no longer related to this repository. I have not implemented /rounds/. Ethereumpool.co has been sold to eth.pp.ua and they have their own fork of this repository, as far i know it's closed source from that moment. I think you should contact eth.pp.ua operator.

**Comment by lukapusic** [comment]
I've contacted them via email, thanks.
