### ISSUE TITLE
COINBASE_ADDRESS

### ISSUE THREAD

**Issue by sademat** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#17]
hi,
what does it mean COINBASE_ADDRESS

because conbase gives an error.
may coinbase adress 0xb902A91f98fD8849923B74Dbc1b955D8483d217e
I1008 21:49:41.107975 eth/cpu_mining.go:35] Cannot start mining without etherbase address: etherbase address must be explicitly specified 

screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8983 --rpc --unlock COINBASE_ADDRESS

**Comment by karek314** [comment]
It seems they have changed that over time, just put there your address on which you want to mine (keystore for that one, must exists)

**Comment by sademat** [comment]
Could you please show an example of usage. 
for this command  screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8983 --rpc --unlock COINBASE_ADDRESS

**Comment by karek314** [comment]
`screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8983 --rpc --unlock 0x5bCbF2CA1b5A7dEB4b534B7C7Ec0cB5E5D724875`

0x5bCbF2CA1b5A7dEB4b534B7C7Ec0cB5E5D724875 - must be valid address stored locally.

https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts
