### ISSUE TITLE
Shares invalid

### ISSUE THREAD

**Issue by bcmonster** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#18]
Everything seems to be working correctly.   If I mine at the web address it gets works.  When a share is found it always come back invalid.   The hash rate shows up on the pool front end as a miner but shows no workers.   Probably due to the fact that no share is ever accepted.   I'm guessing my problem stems from pythereum and or python.   I can't find logs to troubleshoot the reason.   Any help would be greatly appreciated.

**Comment by karek314** [comment]
It's ok. Shares will be almost always invalid. Share is basically solved solution with lower difficulty. We need to submit all shares to verify if this might be our new block. If share is valid it means block has been actually found. There might implemented some sort of pre verification for that, but it may cause delay and our block may become uncle - this is why the best is to keep current solution.

**Comment by bcmonster** [comment]
I guess the word invalid is probably not the correct word.    I also have a Bitcoin pool.    

What I'm getting on the ethminer screen is :( share not accepted .   That is not normal.

**Comment by karek314** [comment]
It seems something changed in geth/parity (not sure what are you using). When i developed this software in past mining software was always returning status "accepted" if share was valid. It was working along with go-ethereum.

If your pool is mining blocks properly you should just modify response from ethereum node right here -> https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/blob/master/mainpage/index.php#L359

**Comment by bcmonster** [comment]
Would pyethereum have anything to do with it? I'm  just know learning the geth commands.    I get emails everyday from people wanting to mine Bitcoin on there PCs so I was going to put up an Ethereum alternative that I can direct those people to.

**Comment by karek314** [comment]
pyethereum is used in this project solely for pow verification.

**Comment by bcmonster** [comment]
![2017-04-10](https://cloud.githubusercontent.com/assets/14815369/24890910/8479b6d6-1e40-11e7-86fe-563716531eef.png)
![2017-04-10](https://cloud.githubusercontent.com/assets/14815369/24890913/86e9c050-1e40-11e7-8516-45635309e213.png)


Just wanted to show you what was happening?  Any clue.   I have not worked on modding the front end yet due to the fact I wanted to make sure I could get it to work.

**Comment by karek314** [comment]
Look at logs, DAG file is still generating - that might be a reason, if not - it must be what i have indicated recently.

**Comment by lordachoo** [comment]
@bcmonster  -- did you ever resolve this?

I've gotten through a lot of issues..this is the last issue i'm stuck on... Been stuck on it for quite a while, everything else seems to work but no shares ever match.

I think something is off about how getWork is running and am trying to research that.



Are the eth_getWork RPC calls supposed to have 0x000 for the DAG?

---------------------------New Query
Method:eth_getWork From IP: xxx
User Hashrate S:12mhash
User payout S:0x04A85782F062B1b958aa6E930802F47C802Ca41C

LAST BLOCK Diff:0x400000000 / 17179869184
LAST BLOCK Time:0
LAST BLOCK Time:1499038488s

Respons1:{"jsonrpc":"2.0","id":73,"result":["0x1bb37ee5d5ead9adfed0a01cdc756bba7448e9e680155df58baab533fbac3be9","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000040080100200400801002004008010020040080100200400801002004"]}

Fixed diff value:720000000
APPKEY:cc658a9f9aff508d0565b1226d9ef9a3
Target:0x00000005f71977b826f3a1ac5dd9589c912450593d593ebf28b737e058fa3d60

Respons2:{"id":1,"jsonrpc":"2.0","result":["0x1bb37ee5d5ead9adfed0a01cdc756bba7448e9e680155df58baab533fbac3be9","0x0000000000000000000000000000000000000000000000000000000000000000","0x00000005f71977b826f3a1ac5dd9589c912450593d593ebf28b737e058fa3d60"]}

**Comment by lordachoo** [comment]
I resolved this, i tested first with this script to test the RPC against my geth

```
#!/bin/bash
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":73}' 127.0.0.1:8983
```

on the latest geth from Ubuntu `geth-linux-amd64-1.6.6-10a45cb5` , it was returning me 0x0000000000... for the middle value (DAG / Seed hash)

i downgraded / re-sync'd to 1.6.5 and it started giving me DAG numbers. This made it so miners pointing at the mining site didn't just start randomly mining..they wait to download the DAG properly.

waiting to see if i run into any other weird issues like this one... but this should help anyone trying to troubleshoot this. I've spent a boat load of time going through misc issues.

**Comment by lordachoo** [comment]
ughhh..that just resulted in repeated DAG refresh / incorrect mining like it was mining old data..now it's fully sync'd again and it's giving 0x0000 responses for seed hash again..

`{"jsonrpc":"2.0","id":73,"result":["0x8f56ece5bed8d64d8ead4bfde63f8bb5aea47dfcfc016c289a317ae65f2f4192","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000040080100200400801002004008010020040080100200400801002004"]}`

**Comment by karek314** [comment]
I guess it's regenerating dag, you need to wait. That's why i dropped this project, almost each version of ethereum had some issues. Like few times geth sent all transactions 2 times, or regularly missed some.
Those are problems very hard to handle for pool operator because morally operator/owner is obligated to pay form own pocket when something get's messed up.

**Comment by lordachoo** [comment]
Yeah. I agree. I think I just wasn't fully sync'd- even though geth would just stop and give out info like it was sync'd .. now i'm forcing it to sync and checking via rpc 


```
#!/bin/bash
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 127.0.0.1:8983
```

Hopefully after that everything works - it looks like it should.. Learned a lot troubleshooting at least..

**Comment by karek314** [comment]
Glad it works.

**Comment by lordachoo** [comment]
I'm having trouble getting it to sync, but at least i figured out the cause, i believe anyway.

It's just not up to date when it says it is..

If I get 0x00000000000 for the DAG from Geth it's DEFINITELY not right, right?

Also it's not generating the large DAG files (the 1GB ones by default) - that happens at the very end when its up to the highest block , right?

My questions are mainly dumb unrelated questions-- If i had known this stuff before hand troubleshooting path would have been much clearer. Thanks for replying!

**Comment by karek314** [comment]
Did you tried launching geth with parm "--fast" or something similar, as far i checked recently, on quite decent but not very powerful server, geth can't properly sync from beginning. I mean it's not possible to catch up with recent network height with full verification without really good dedicated server. That's why using --fast may help, but it's not good for decentralisation.

**Comment by lordachoo** [comment]
I always use --fast in my script, do i need to just run geth --fast by itself to sync first? It doesn't seem to do anything 'fast'.

Seems like it's stuck basically, keeps stalling out or syncing only a few blocks at a time:

`{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x24ff64","highestBlock":"0x3c90c1","knownStates":"0x0","pulledStates":"0x0","startingBlock":"0x24f9b6"}}`

Which is only like 2.4B blocks out of ~4B

**Comment by karek314** [comment]
--fast is still quite fast. Run it without --fast as advised. Then you won't sync client to recent height without very powerful dedicated server. If your node is still behind best height, or randomly gets behind. Maybe your server is overloaded causing problems with geth.
