### ISSUE TITLE
 README: `Recommended HHVM over php5-fpm, but fastcgi is fine.`

### ISSUE THREAD

**Issue by ramvi** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#3]
The README.md states:
> Recommended HHVM over php5-fpm, but php5-fpm is fine.

Is it supposed to be `Recommended HHVM over php5-fpm, but fastcgi is fine.`

**Comment by karek314** [comment]
Not really. fastcgi is only interface between codebase and webserver.
More info -> https://en.wikipedia.org/wiki/FastCGI
