### ISSUE TITLE
"Fake shares" attack resistant and Double nonce 

### ISSUE THREAD

**Issue by mmitech** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#5]
Just came across the issue that most pools had with the Fake shares attack, how do this pool do against these attacks ?

**Comment by karek314** [comment]
python script **nonce_fast.py** verify all shares submitted since last processed block, in case share is fake, then will be delated and won't be used in calculations.
Read more about ethpow

**ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)**

**Comment by ramvi** [comment]
Impressive feedback here!

Den tirsdag 9. februar 2016 skrev karek314 <notifications@github.com>
følgende:

> python script *nonce_fast.py* verify all shares submitted since last
> processed block, in case share is fake, then will be delated and won't be
> used in calculations.
> Read more about ethpow
>
> *ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/issues/5#issuecomment-182103613>
> .
>


-- 


*Jon Ramvi408 70 027*
