### ISSUE TITLE
Block found but not credited (wasn't split among miners)!!!

### ISSUE THREAD

**Issue by mmitech** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#6]
I see this in the logs 

 ````   
--------------NEW BLOCK SOLVED--------------

balance:10394990954051287296
b_size_init:0
Blocksize normal PLAIN
Lenght1:1
Lenght2:20
Lenght1:0
Lenght2:12000000000000000000
Block size:0
Pool fee:99% for miner
Current block: "Current Block"
Coinbase:0xd21b733104b48c5c09921457f97f5acc06b42d49
Balance: 10394990954051287296 wei
Block: "Block#" has been mined!

0 wei to split
Block MINYED BY: COINBASE ADDRESS
15110/0/15116
Shares:15075
TimeRange:94.883333333333 minutes
=============================================================================
Total Miners Diff:10266825000000  =  0 wei
'MINER1' => 1695015000000 => 0 wei =>0.000000
'MINER2' => 1732425000000 => 0 wei =>0.000000
'MINER3' => 1576050000000 => 0 wei =>0.000000
'MINER4' => 1737705000000 => 0 wei =>0.000000
'MINER5' => 1769820000000 => 0 wei =>0.000000
'MINER6' => 659955000000 => 0 wei =>0.000000
'MINER7' => 1095855000000 => 0 wei =>0.000000
10266825000000/10266825000000PHP Warning:  bcdiv(): Division by zero in /var/www/html/eth-pool/BigInteger.php on line 1416
PHP Warning:  bcmod(): Division by zero in /var/www/html/eth-pool/BigInteger.php on line 1417

0/0/0
Pool fees revenue: 0 wei => 
DIFF Number Correct!
Wei Balance without fee Correct!
Wei Balance with fee Correct!

One block found



=====LOOP DONE=====

sleeping...
Round:468
state_work null
````

Some blocks are credited some are not !!! what is the problem here ? I tried to look through the block_processing and I can't understand the standard block size meaning !!?
````
$standart_block_size = new Math_BigInteger('5000010000000000000');
````
Yes, Ethereum is completely different than what I am used to(Bitcoin and  Alts), I am trying to learn in the process...

**Comment by karek314** [comment]
I guess this issue might be related to third party service while getting balance from independent node, (you can get from current node, but it will create even more trouble since sometimes forks happen in blockchain and balance will be incorrect). I suggest to debug response from third party service, and if response is valid, maybe the best solution will be to setup new node on cheap vps to just get balance, or use 2 different services to compare balance. Im not sure how does it look like now, i no longer develop this project.

**Comment by mmitech** [comment]
What is the third party service here ?

**Comment by karek314** [comment]
**$ch1 = curl_init('http://api.etherscan.io/api?module=account&action=balance&address='.$addrr[0].'&tag=latest'); **                                                                                                                   

There are few workarounds with this, easiest one should be getting balance and last block data from independent node instead current mining node.

you can try set --maxpeers "250" , more connected nodes should reduce forks, so it might help.

**Comment by mmitech** [comment]
OK, so what this has to do with splitting reward ?

**Comment by karek314** [comment]
Splitting script checks if last block on blockchain has been mined by your node, sometimes this response may be invalid (incase local fork on blockchain) - splitting script takes balance from independent node so actually value to split will be equal to "0", but your node still thinks that has mined block. Usually it's fixed after next propagated block. Possible easy ways to fix it: 1.delay script for 1 block to make sure data is correct. 2.Get last block data from independent node 3.Or entirely rewrite splitting script.

Hope it's clear now, if you fix it, i will be glad to merge your request to master branch.

**Comment by mmitech** [comment]
I think the problem relies in calling a third party service. You solve the block but the time it needs to propagate through network + time to validate it + add to the DB and serve it through the third party service API is too long.

How do you solve this in your Live Pool ? How do I delay the script for one block in this case ?

**Comment by mmitech** [comment]
OK a dirty fast fix for this, I add sleep(10) before :
````
$ch1 = curl_init('http://api.etherscan.io/api?module=account&action=balance&address='.$addrr[0].'&tag=latest');  
````

this should give it a bit more time to get real balance.

**Comment by karek314** [comment]
I didn't experienced this issue much, at time i have exchanged with other pools ips and node id, so i didn't have local forks. According to third party service, it was quick fix - the better way will be cheap vps with eth node. Or the best way, just rewrite script to handle local forks.

**Comment by mmitech** [comment]
How often local forks happen ?
I will have to rewrite it to call another local node in case of local forks, I removed the third service completely now will see how that works out.

**Comment by karek314** [comment]
It's really hard to predict, it depends on many factors. Generally, the worst propagation your node has, more local forks and uncles will occur.

**Comment by mmitech** [comment]
Fixed this, I had two problems: 
1- Geth that was installed from ubuntu ppa-repository was throwing JSON errors which messed up the block processing, I had to download the release directly from GitHub.
2- relying on Third party services isn't ideal, so installing an additional node to validate a block is better.

One other thing, this code here is outdated for sure, in your live pool you have many different things that are not available here, I would be thankful if you update this project with changes you made to your live pool and I will work on adding the next improvements/features:

- Adding email monitoring for workers.
- Get rid of the third party services.
- Changing the way miners get credited (only when the block have 375 confirmations)
- Some UI improvements.

Please update the project and I will work on top of the newer version and PR.

**Comment by ramvi** [comment]
> this code here is outdated for sure, in your live pool you have many different things that are not available here, I would be thankful if you update this project with changes you made to your live pool 

+1

**Comment by karek314** [comment]
To clear things out, I'm no longer running pool. This is latest available code i have used. 
**Ethereumpool.co** domain has been sold to **eth.pp.ua** which is another fork of my code. I just didn't have much time to develop further and mange this project.
