### ISSUE TITLE
"Invalid header on mined Block" crashes client

### ISSUE THREAD

**Issue by ramvi** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#7]
I was puzzled when I read issue #4, because when a client connects to my pool and submits its solution, the client crashes. Both `alethone` and `ethminer`. I have no idea why geth's response to the client crashes my clients, but works in issue #4.

**Comment by karek314** [comment]
Please include more details, which version of geth and ethminer are you using? It must be related to miner itself. Pool script just pass response from geth so everything should be fine. Please make sure to build geth from latest development branch https://github.com/ethereum/go-ethereum and latest get ethminer. If issue still occur you can try enable logging in mainpage/index.php

**Comment by ramvi** [comment]
Thanks for the reply!

Running geth v1.4 built from branch `develop` and a new ethminer. The logging in `mainpage/index.php` shows, when the miner crashes:
```
---------------------------New Query
Method:eth_submitWork From IP:xxx
User Hashrate S:6mhash
User payout S:0x002107xxxxx
\Work:{"id":1,"jsonrpc":"2.0","method":"eth_submitWork","params":["0x21bxxxxx","0x62fxxxxx","0x2adaxxxxx"]}


Response:{"jsonrpc":"2.0","id":1,"result":true}

APPKEY:8fcxxxxx
==========================================================================
=======================WORK HAS BEEN SUMBITED=============================
User:0x002xxxxx
UserDiff:0x0000000beexxxxx
DiffDecimal:360000000
BlockDiff:0
BlockPowHash:0x62fxxxxx
RealBlockTarget:0x0000000000189xxxxx
SeedHash:0x1978xxxxx
Block Number:1 / 1
==========================================================================
NonceFound:0x21bxxxxx
PowHash:0x62fbxxxxx
MixDigest:0x2axxxxx
==========================================================================
==========================================================================
```
Then it stops

**Comment by ramvi** [comment]
I'm also testing with AlethOne. I point it to an other pool e.g. eth.uu.ua and it works great. I point it to this project and it crashes after a minute or two.

**Comment by karek314** [comment]
Please include un-cuted log with full hashes not 0x62fbxxxxx ... And also url to mining. i will check that.

**Comment by ramvi** [comment]
Thankd, will do. I shut down my digital ocean droplet, so give me some time
to get it back up.

Den lørdag 13. februar 2016 skrev karek314 <notifications@github.com>
følgende:

**Comment by ramvi** [comment]
I took my droplet down. I could set the system back up, but I think I'm just going to leave it and close this. Thanks for replying!

**Comment by karek314** [comment]
I see you closed issue, problem remains gone?

**Comment by mmitech** [comment]
I think he dropped the project all together, the truth is the performance of this pool is horrible, I also dropped it for the same reason, once we pointed more than 3 GHs miners were not getting work and they were having problems connecting at times.

**Comment by karek314** [comment]
Performance depends much on configuration, I was running smoothly with 12ghash at peak with less than 10% cpu, which mostly consumed geth, it was 12cores dedicated server. He mentioned about droplet, vps is not good idea to run anything bigger than private blog.

**Comment by mmitech** [comment]
really ?!! I had 12 core server with 24 GB ram and HHVM with nginx and it was really performing bad. and the CPU cores were at 75% most of the time (geth and HHVM)

now you caught my attention, I am curious how did you achieve that ?

**Comment by karek314** [comment]
With geth consuming nothing you can do. It's all about configuration i dont know how did you configured mysql server, hhvm etc. This is not topic for Issue with code.

**Comment by mmitech** [comment]
OK I redeployed the server again, I spent a bit more time working on HHVM and nginx settings, will deploy 8 GHs mining power and see what happens.


BTW, don't get me wrong, I appreciate the work you did and even more making it open source, I wasn't talking about the quality of your code but the "shitiness" of php in general when it comes to performance.

**Comment by ramvi** [comment]
> With geth consuming nothing you can do

Maybe it's possible to run with less overhead if changing `geth` with [Parity](https://ethcore.io/parity.html). It's the the most lightweight Ethereum implementation written in Rust.

> the "shitiness" of php in general when it comes to performance

Can't really see that being a problem with a lot of memory and HHVM. HipHop VM runs Facebook in PHP. But it needs to be all pre-compiled and put in RAM to reach top performance.

**Comment by karek314** [comment]
Actually php is not bad. Many big sites uses php. Its hard to compare languages but this chart can show kind a draft of performance.
http://blog.carlesmateo.com/wp-content/uploads/2014/10/blog-carlesmateo-com-performance-several-languages-php7-phantomjs-nodejs-java-bash-go-perl-luajit-hhvm3_9-scale_mod5.png

**Comment by mmitech** [comment]
Only 3.5 GHs and then miners will start disconnecting...

I start all scripts with 
````
 hhvm  -v Eval.Jit=1 -v Eval.JitWarmupRequests=0 -v Eval.PerfPidMap=false /somephp.php
````
my nginx config:

````
server {
        listen  80 default_server;
        listen [::]:80  ipv6only=on;
        listen 443 ssl default_server;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        server_name localhost;

        root /var/www/eth-pool/mainpage;
        index index.php index.html index.htm;

        rewrite ^/sitemap_index\.xml$ /index.php?sitemap=1 last;
        rewrite ^/([^/]+?)-sitemap([0-9]+)?\.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;


        location / {
        try_files $uri $uri/ /index.php?$args;
        }

        error_page 404 /404.html;

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
                root /usr/share/nginx/html;
        }

        location ~ \.(hh|php)$ {
                fastcgi_pass unix:/var/run/hhvm/hhvm.sock;
                fastcgi_keep_conn on;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_buffer_size 128k;
                fastcgi_buffers 256 16k;
                fastcgi_busy_buffers_size 256k;
                fastcgi_temp_file_write_size 256k;
                fastcgi_read_timeout 240;
                fastcgi_intercept_errors on;
                include        fastcgi_params;

        }

        location ~* .(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe$
        expires max;
        log_not_found off;
        access_log off;
        }
}

````



![2016-02-17 10_31_09-office - 94 140 77 242_5017 - remote desktop connection](https://cloud.githubusercontent.com/assets/4456920/13105111/a87bbf76-d561-11e5-901c-feb76f00b90f.jpg)

**Comment by mmitech** [comment]
OK, I will just add that not only my pool is horribly performing but even ethereumpool.co.
You can try pointing your miners and see what happens

![2016-02-17 13_14_23-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/4456920/13109271/8b660af6-d578-11e5-815e-254bfdae95f8.jpg)

**Comment by karek314** [comment]
Im not managing ethereumpool.co anymore, it's not on my servers. Actually ** Failed to submit hashrate** appears to be difference between your miner and pool api. It seems main mining script needs changes with hash rate submitting to fit new version of miner.

According to your problem, please check how many open tcp/ip connection you have. If value is fairly high try 
**sysctl -w net.ipv4.tcp_tw_recycle = 1**
or/and
**sysctl -w net.ipv4.tcp_tw_reuse = 1**

but it's kind like read the tea leaves without access to server and debug it.
